### ISSUE TITLE
Move code coverage from coveralls.io to codecov.io

### ISSUE THREAD

**Issue by danieldietrich** [javaslang/javaslang-jackson#14]
Just did it for Javaslang. Looks awesome!

* [Coverage](https://codecov.io/github/javaslang/javaslang?branch=master)
* [Changes](https://github.com/javaslang/javaslang/pull/765/files)

**Comment by ruslansennov** [comment]
wow! 
https://github.com/codecov/browser-extension#codecov-extension

**Comment by danieldietrich** [comment]
Yes, really cool!

**Comment by danieldietrich** [comment]
Think it does work all now - will close it.
