### ISSUE TITLE
Cannot Correctly Deserialize TreeMap and HashMap with non-string keys 

### ISSUE THREAD

**Issue by jasoet-gdp** [javaslang/javaslang-jackson#26]
As discussed at #25, javaslang-jackson currently not able to Deserialize TreeMap and HashMap with non-string keys correctly.

```java
 final TreeMap<Integer, Double> src = TreeMap.of(Tuple.of(42, 42.0));

final String json = mapper().writer().writeValueAsString(src);
final TreeMap<Integer, Double> fromJson = mapper().readValue(json, new TypeReference<TreeMap<Integer, Double>>() {});

Assert.assertEquals(src,fromJson);
```
 
Keys from TreeMap/HashMap object from JSON with non-string keys  converted to String during Deserialization.

![screen shot 2015-11-18 at 3 30 21 pm](https://cloud.githubusercontent.com/assets/12537951/11236251/b76c42ba-8e0a-11e5-96cd-e2db8c7a10e3.png)

**Comment by ruslansennov** [comment]
> Keys from TreeMap/HashMap object from JSON with non-string keys converted to String during Deserialization.

No. During serialization. See [this](https://github.com/javaslang/javaslang-jackson/blob/master/src/main/java/javaslang/jackson/datatype/serialize/MapSerializer.java#L34)
