### ISSUE TITLE
Either serialization is not according to its semantic

### ISSUE THREAD

**Issue by atrianac** [javaslang/javaslang-jackson#54]
I think the Either serialization is not according to its semantic. Either could be Left or Right (but not both), for example a field with value `Either.right(R right)` is serialize to `{"either":[null,R]}`, but it should be only  `{"either":R}`.

**Comment by ruslansennov** [comment]
I believe there will be problems with deserialization in your case. For example, what's right answer for deserialization <code>{"either":42}</code> to <code>Either&lt;Integer, Integer&gt;</code>? It will be left or right?

**Comment by atrianac** [comment]
I think it should be always right. I know we can lost information here, but if you notice Either semantic always works with right value (isEmpty and getOption)

**Comment by ruslansennov** [comment]
Either semantic prefers right value, but works also with left value well.
```java
void eitherTest() {
    Either<Integer,Integer> either = Either.right(42);
    assert !either.isEmpty();
    assert !either.right().isEmpty();
    assert either.left().isEmpty();
}
```
But if <code>Either.Left</code> after serialization/deserialization will be <code>Either.Right</code> it can break user logic.

/cc @danieldietrich

**Comment by atrianac** [comment]
Yes @ruslansennov you right, This is a problematic thing, for example, how should the behavior when we use @JsonIgnore annotation for an Either field?

**Comment by atrianac** [comment]
Sorry, when we use @JsonInclude(NotNull)

**Comment by ruslansennov** [comment]
Hmmm... I have no idea. Maybe user must be aware that he does :smile:

**Comment by danieldietrich** [comment]
@atrianac, @ruslansennov without diving too deep into technical details, the combined operation `deserialize(serialize(either)) =: either'` should result in `either'` such that `either.equals(either')`. That is our invariant. Serialization does not perform any kind of transformation.

It is right that our Either implementation is right-biased. But we should not confuse _operations_ on an Either instance with the _state_ of an either instance. The state has to be preserved.

Without knowing the json framework I would encode/serialize the _type_ and the _value_ of an instance...

Just my 2 cent (€)

**Comment by ruslansennov** [comment]
> Without knowing the json framework I would encode/serialize the type and the value of an instance...

Something like <code>{"either": ["left", 42]}</code>
It's possible

**Comment by danieldietrich** [comment]
This is the way to go!
