### ISSUE TITLE
Option: undefined gets deserialized as null

### ISSUE THREAD

**Issue by emmanueltouzery** [javaslang/javaslang-jackson#57]
If I add this test to `OptionTest.java`, I get a test fail:

```
    private static class SimpleObject {
        public Option<Integer> value;
    }

    @Test
    public void testUndefinedDeserialization() throws IOException {        
        SimpleObject restored = mapper().readValue("{}", SimpleObject.class);
        Assert.assertEquals(Option.none(), restored.value);
    }
```

In other words, `undefined` gets deserialized to `null`instead of the expected `Option.none()`. That's a major setback, but then I have no idea whether jackson would allow to fix that.

**Comment by ruslansennov** [comment]
Hi @emmanueltouzery 
Thank you for your feedback
It seems we should store additional flag, something like `{"opt": ["defined", null]}` or `{"opt": ["undefined"]}`
See #54

**Comment by emmanueltouzery** [comment]
I don't know, I think if a field is `Option` it should never be null, otherwise it really gets messy. So ideally no flag, as I think it's clear what's the right thing to do. Probably you're concerned about backwards compatibility?

Personally I'm afraid that jackson doesn't even allow this at all :-(

**Comment by ruslansennov** [comment]
> I think if a field is Option it should never be null, otherwise it really gets messy

No, it makes sense that there is a `Some(null)`. There are a few use-cases where this is needed. 
(See a [recent discussion](https://github.com/javaslang/javaslang/pull/1180))

> Probably you're concerned about backwards compatibility?

Unfortunately, backward compatibility is already compromised by `Either`. Upcoming version is 2.1.0 and we still can additionally change algorithm of `Option`'s encoding/decoding

**Comment by emmanueltouzery** [comment]
alright, I get it. So today, `undefined -> null`.
In 2.1, you could be able to say => `undefined -> Option.none() OR undefined -> Option.some(null)`.

I guess in no case, ever, should it deserialize to `null`, as it does today, though.

**Comment by ruslansennov** [comment]
We can do something like this:

**Serialization**

Option.none() -> ["undefined"]
Option.some(value) -> ["defined", value]
Option.some(null) -> ["defined", null]

**Deserialization**

["undefined"] -> Option.none()
["defined", value] -> Option.some(value)
["defined", null] -> Option.some(null)

**Comment by emmanueltouzery** [comment]
presumably if the user says nothing the default is `["undefined"]`? Otherwise sounds great, I hope it makes it in 2.1!

**Comment by ruslansennov** [comment]
> presumably if the user says nothing the default is ["undefined"]? 

Yep

> Otherwise sounds great, I hope it makes it in 2.1!

PR are welcome :)

**Comment by emmanueltouzery** [comment]
i would work on it but I am still under the impression that jackson may not support it.

OptionDeserializer already contains this:

```
    @Override
    public Option<?> getNullValue(DeserializationContext ctxt) {
        return Option.none();
    }
```

So there is a custom handling for `null` in jackson. I am not sure how to handle `undefined` with jackson, or even whether it's possible.

**Comment by ruslansennov** [comment]
OptionDeserializer may look like [EitherDeserializer](https://github.com/javaslang/javaslang-jackson/blob/master/src/main/java/javaslang/jackson/datatype/deserialize/EitherDeserializer.java) (updated few minutes ago, thank you again)

**Comment by emmanueltouzery** [comment]
I am pretty confused by the change in the end..
If the json contains eg "6" and we want to deserialize to Option<Integer>, we still get Option.of(6) right?
And Option.of(6) goes to "6" by default in the json? Or we actually use these (non idiomatic) arrays in the json?

I thought you were talking about options for the setup of javaslang-jackson, actually binding to arrays would break our use-case and not suit us at all :-(

**Comment by emmanueltouzery** [comment]
(i think my goal is interop with idiomatic json and your goal is 1:1 matching between java and json and the goals don't match at all.

I would have, for Option<Integer> for instance:

undefined -> none()
null -> none()
"sff" -> none()
6 -> of(6)

of(6) -> 6
none() -> null

I'm sorry that i read you way too fast the first time. I hope if it's not the default operation, some setting could enable that operation mode?

**Comment by emmanueltouzery** [comment]
so I understand, you want to support Some(null). However I think most projects don't need that but have a much more pressing need for idiomatic interop with JS. Do you think a global option for javaslang-jackson is possible? That would enable either 1:1 conversion including Some(null), or idiomatic JSON? Should I open a bug about that, or you won't accept that in javaslang-jackson?

**Comment by ruslansennov** [comment]
Option deserialization (Either deserialization also) is the pain in the ass :(
Here is my logic of last change:
* Option can be defined (with any value including null) or undefined
* Therefore we should store this property (defined/undefined) in json for correct deserialization of null

Now this your comment

> Or we actually use these (non idiomatic) arrays in the json?

is true. We have non-idiomatic but correct json-format for storing Option.
I understand your frustration and I like your idea about options for the setup of javaslang-jackson module. Something like enum `OptionDeserializationMode { ARRAY, PLAIN }`

**Comment by emmanueltouzery** [comment]
Ok I'm glad the option is acceptable to you. Do you think you'll make it for 2.1 or should I try to prepare a PR? That one is really important to me and if you don't plan to make it for 2.1 I'll work on it.

**Comment by ruslansennov** [comment]
> Do you think you'll make it for 2.1

I'll try to implement this soon. Maybe it will be two setup option:

* `Option` will be encoded/decoded as array or as plain value. I'm not sure which behavior should be default
* `null` will be decoded as `Option.none()` or as `Option.some(null)`

**Comment by ruslansennov** [comment]
@emmanueltouzery Option encode/decode default behavior reverts to [701c652](https://github.com/javaslang/javaslang-jackson/tree/701c652d2adddbd4430d6eb4113ac5d2ef2d33f7)  and setup options added.
Regarding your initial requiest, please see [BeanAnnotationTest.java](https://github.com/javaslang/javaslang-jackson/blob/701c652d2adddbd4430d6eb4113ac5d2ef2d33f7/src/test/java/javaslang/jackson/datatype/bean/BeanAnnotationTest.java). There we have initial `field`'s value which does not change when empty json deserialize. I have no other ideas
