### ISSUE TITLE
Release 2.0.3 does not include pull requests since April

### ISSUE THREAD

**Issue by zsolt-donca** [javaslang/javaslang-jackson#72]
The recent `2.0.3` release was made from the old branch [`v2.0.x`](https://github.com/javaslang/javaslang-jackson/commits/v2.0.x) with the last commit being from _Apr 4, 2016_, making the new `2.0.3` release **practically identical** to the release `2.0.2` (see the branch history).

This, in practice, means that nothing developed in the last four months has been released, including the following pull requests:

#52 Add null default serializer in order to support ignore annotations
#53 PriorityQueue support
#55 combines Seq, Set & PQ serializers to ArraySerializer 
#56, #58, #59 'Either' semantic changed; deserialization fixed; refactored
#60 Option.some(null) & Option.none() serialization
#61 Option encode/decode mode
#63 Serialization features support
#65 Fixed a `JsonMappingException` error when deserializing various types
#67 Add ability to use polymorphic types
#68 Desearialize nulls as empty collections

In my opinion, a new release should be made that should contain the latest changes and bugfixes. It should contain, at least, the changes up to #63 (as that's a critical one).

<h2>Background</h2>
 We have been using _javaslang_ and _javaslang-jackson_ for a couple of months in a commercial project. Since we are **critically dependent** on the fix of #63, in the last 10 weeks, we've been using the snapshot version `2.1.0-SNAPSHOT`, directly from to maven central (built automatically when the github repo changes). Yesterday, our builds started to fail, because `2.1.0-SNAPSHOT` just went back in time four months. We've seen that this coincides with the new `2.0.3` release, so we tried using that one. However, our code still did not work. Currently, our only option is to use the newest snapshot (`3.0.0-SNAPSHOT`), but we would want to avoid using snapshot dependencies so as much as possible.

**Comment by danieldietrich** [comment]
I think we need to make a clean 2.1.0 release as soon as possible for both, javaslang and javaslang-jackson. This should include the work of the last months that is backward compatible.

javaslang-jackson depends on javaslang. So the javaslang-2.1.0 release needs to be made first. Looks like I will to start cherry-picking / `git rebase -i`-ing today...

**Comment by ruslansennov** [comment]
Hi @zsolt-donca , @danieldietrich 
Yes, I plan to make lot of cherry-picks during javaslang-jackson.2.1.0 preparing

**Comment by zsolt-donca** [comment]
What is the reason behind making the new `2.0.3` release practically identical to the `2.0.2`? Just to follow the same versioning of _javaslang_?

**Comment by danieldietrich** [comment]
Yes. But I think the patch versions should be independent of each other, e.g.

`javaslang-<major>.<minor>.<patch>` and `javaslang-jackson-<major>.<minor>.<patch>` should be compatible independent of the `<patch>` version. In particular the `patch` versions may differ. Always taking the actual patch release is the way to go.

`javaslang-jackson` should follow `javaslang` regarding `<major>.<minor>` because it depends on it.

This should be part of our semantic versioning. We will take care of it.

If you have suggestions regarding the (future) versioning, please tell us!

**Comment by zsolt-donca** [comment]
As long as `javaslang-jackson` only uses the public API of `javaslang`, not depending on any internal implementation detail (neither is that needed nor would it be a good idea). The backwards/forwards compatibility rules of `javaslang` with regards to versioning should define the relationship between the two.

I'm not sure of javaslang's compatibility rules, so let's take an example. If `javaslang` can potentially break compatibility between major versions, but offers backwards compatibility for minor versions, then, for any new major release of `javaslang` there should be a new `javaslang-jackson` release. If the minor releases are used for introducing new features (but otherwise keeping backwards compatibility), then it shouldn't matter what version of `javaslang` and `javaslang-jackson` is used: in worst case, the new javaslang features (e.g. a new collection) cannot be serialized or deserialized with using an old jackson module (which is to be expected). A newer jackson module should always work with an older javaslang module, as long as it's the same major version.

**Comment by zsolt-donca** [comment]
As long as `javaslang-jackson` only uses the public API of `javaslang`, not depending on any internal implementation detail (neither is that needed nor would it be a good idea). The backwards/forwards compatibility rules of `javaslang` with regards to versioning should define the relationship between the two.

We also should keep in mind the main purpose of `javaslang-jackson`: to serialize/deserialize various `javaslang` collection types.

I'm not sure of javaslang's compatibility rules, so let's take an example. 

- Assuming that `javaslang` can potentially break compatibility between major versions, but offers backwards compatibility for minor versions, then, for any new major release of `javaslang` there should be a new `javaslang-jackson` release, with the same major version. 
- If a new `javaslang` minor release introduces a new collection type (which is a backwards-compatible change), then a new `javaslang-jackson` version should be released, with the same minor version, that supports serialization/deserialization of the new type. It is safe to only release in this case as breaking changes are not allowed in minor releases (that's what major releases are for).
- If patch releases are only for fixing bugs, then there shouldn't be any correlation between the releases of `javaslang` and `javaslang-jackson`. This would also allow faster fixing of bugs in `javaslang-jackson`; just think of #63 that makes `javaslang-jackson` **practically unusable** in any non-trivial jackson configuration.

I can see the benefit of having the same versioning for both `javaslang` and `javaslang-jackson`, but the costs (slower fixing of bugs, binary releases with the very same content) outweigh the benefits (easier dependency management).

What are your thoughts?

**Comment by danieldietrich** [comment]
@zsolt-donca 

> Since we are critically dependent on the fix of #63, in the last 10 weeks, we've been using the snapshot version 2.1.0-SNAPSHOT, directly from to maven central (built automatically when the github repo changes).

Never ever depend on a SNAPSHOT, it is subject to change. I think the right direction is to bring new features more frequently into production.

**Comment by danieldietrich** [comment]
@zsolt-donca 

> What are your thoughts?

I share exactly your opinion on versioning. We will do it like that.

The challenge is to keep track of potentially breaking refactorings of javaslang core types can be solved by running javaslang-jackson tests before a release. Is Github able to trigger CI build chains across project boundaries?

**Comment by danieldietrich** [comment]
@ruslansennov Will the new Vector be compatible to the current serializer/deserializer of javaslang-jackson? I need to know whether to include it in 2.1.0 or not...

**Comment by ruslansennov** [comment]
> Will the new Vector be compatible to the current serializer/deserializer of javaslang-jackson? I need to know whether to include it in 2.1.0 or not...

As I know, no public API was changed in `Vector`.
So, please include it

**Comment by danieldietrich** [comment]
Will do!

**Comment by ruslansennov** [comment]
2.0.4 released
