### ISSUE TITLE
SortedSet tries and fails to be serialized as HashSet

### ISSUE THREAD

**Issue by kag0** [javaslang/javaslang-jackson#73]
Like title says.

this line in `SetDeserializer.create`
```java
if(javaslang.collection.TreeSet.class.isAssignableFrom(javaType.getRawClass()))
```
should be 
```java
if(javaslang.collection.SortedSet.class.isAssignableFrom(javaType.getRawClass()))
```
(TreeSet is not assignable from SortedSet)

I'll put in a PR in a couple hours if you guys are open to it.

**Comment by ruslansennov** [comment]
We are open, thank you

**Comment by danieldietrich** [comment]
Do we fulfill the following 'invariant'?

```java
deserialize(serialize(o)) equals o
```

**Comment by ruslansennov** [comment]
@danieldietrich that makes sense
