### ISSUE TITLE
JsonTypeInfo feature not well supported

### ISSUE THREAD

**Issue by emmanueltouzery** [javaslang/javaslang-jackson#76]
I have added a failing test in a branch of mine:
https://github.com/emmanueltouzery/javaslang-jackson/tree/jsontypeinfo_issue

commit https://github.com/emmanueltouzery/javaslang-jackson/commit/0b79bd6d9b086f0aeb0c96887cd17f5887e154af

I have stumbled in a codebase I'm working on on a use of that @JsonTypeInfo feature; with this example, we get a different serialization with javaslang.collection.List as opposed to java.util.List. It's hampering our migration to javaslang.
Sadly I have no idea how to fix this in javaslang-jackson...

The test failure prints:

    Failed tests:   testJsonTypeInfo(javaslang.jackson.datatype.seq.ListTest):
    expected:<{"f":[{"[card":{"type":"hello"}]}]}>
    but was: <{"f":[{"[type":"hello"]}]}>

**Comment by ruslansennov** [comment]
I'll take a look, thank you

**Comment by ruslansennov** [comment]
@emmanueltouzery please review #77 
Maybe you can suggest other tests to verify this PR more precisely?

**Comment by emmanueltouzery** [comment]
wow, this looks great thank you!
I've looked a bit in our codebase for other use cases of that API (which I had never seen before), but it seems it's only being used in that scenario that I extracted for the test. I've tried to port it over to Set from List and with your patch it works as well...

So I guess it's good for master, of course if I spot other issues I'll report but so far I'm not aware of any.

PS: will this go in the 2.1 release, or will it wait for the 3.0 one?

**Comment by danieldietrich** [comment]
Should go into the 2.1. Nothing will break, right @ruslansennov

**Comment by ruslansennov** [comment]
> So I guess it's good for master, of course if I spot other issues I'll report but so far I'm not aware of any.

No, I found some problems with `Option` and `Either`. I will prepare fixes soon

> Should go into the 2.1

Hope I will be able to release all fixes with 2.0.4
Hope nothing will break in API :)
