### ISSUE TITLE
OptionSerializer fails to serialize parameterized/wildcard Option fields

### ISSUE THREAD

**Issue by mpulkkinen** [javaslang/javaslang-jackson#80]
adding the following to OptionPlainTest:

    public static class Parameterized<T> {
        public Option<T> value;
        public Parameterized(Option<T> value) {
            this.value = value;
        }
    }
    
    @Test
    public void writeWrappedParameterizedSome() throws IOException {
        Parameterized<Integer> object = new Parameterized<>(Option.some(1));
        assertEquals("{\"value\":1}", mapper().writeValueAsString(object)); 
    }
    
gives:
> com.fasterxml.jackson.databind.JsonMappingException: No serializer found for class java.lang.Integer and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) ) (through reference chain: javaslang.jackson.datatype.Parameterized["value"])
    at com.fasterxml.jackson.databind.ser.impl.UnknownSerializer.failForEmpty(UnknownSerializer.java:69)
    at com.fasterxml.jackson.databind.ser.impl.UnknownSerializer.serialize(UnknownSerializer.java:32)
    at javaslang.jackson.datatype.serialize.ValueSerializer.serialize(ValueSerializer.java:53)
    at javaslang.jackson.datatype.serialize.OptionSerializer.serialize(OptionSerializer.java:41)
...

same happens with Option<?> and in "array" serialization mode

**Comment by ruslansennov** [comment]
Hi @mpulkkinen 
Which version you are using?

**Comment by mpulkkinen** [comment]
first noticed using 2.0.4, wrote that test using latest master 3...

**Comment by ruslansennov** [comment]
thank you, I'll tale a look

**Comment by ruslansennov** [comment]
@mpulkkinen please check `3.0.0-SNAPSHOT`
@danieldietrich I plan to release next bugfix release. The version will be `2.0.4.1`. What's your opinion about fourth digit?

**Comment by danieldietrich** [comment]
@ruslansennov we have to re-release *every* Javaslang module then when the core is released, even if the module did not change.

It will save us from total chaos, if we have to break compatibility for some reason. But it is only a matter of organisation to get semantic versioning right.

I would keep major and minor in sync and use the patch version for each module on its own.

**Comment by mpulkkinen** [comment]
@ruslansennov seems to work, closing
