### ISSUE TITLE
XML-specific annotations

### ISSUE THREAD

**Issue by emmanueltouzery** [javaslang/javaslang-jackson#82]
jackson supports also XML serialization and deserialization through some extra dependency, and even JAXB XML-specific annotations. Those don't work with javaslang-jackson.. That may be on purpose (jackson supports so many features, it's really difficult to support it all), but in case you actually intend to support these use cases, I added two failing tests: one using jackson XML-specific annotations, and one using JAXB annotations.

In the tests I serialize the "same" object, once with java.util.List, once with javaslang.collections.List, and expect the same XML output. I commited the test in the xml_annotations branch of my fork, in commit https://github.com/emmanueltouzery/javaslang-jackson/commit/6fbad5f8a0bbeb18134b0fe5ce30b81d8ec860cc

**Comment by ruslansennov** [comment]
Until now it is only `csv` used here :)
thank you

**Comment by ruslansennov** [comment]
It seems that the problem is localized [here](https://github.com/FasterXML/jackson-dataformat-xml/blob/jackson-dataformat-xml-2.6.5/src/main/java/com/fasterxml/jackson/dataformat/xml/ser/XmlBeanSerializerModifier.java#L54). 
`java.util.ArrayList` is an Jackson indexed type, but `javaslang.collection.List` is not.

**Comment by emmanueltouzery** [comment]
I was looking a little more...
I think the criteria is inheritance from `java.util.Collection`, or being a raw array, which we obviously don't have.

Following the call, we find [this](https://github.com/FasterXML/jackson-dataformat-xml/blob/jackson-dataformat-xml-2.6.5/src/main/java/com/fasterxml/jackson/dataformat/xml/util/TypeUtil.java#L16).

they call `JavaType.isContainerType`. Also line 35 of that same file, in another codepath, they do `Collection.class.isAssignableFrom(cls)` (and array check).

in jackson, `JavaType` is constructed only in [TypeFactory](https://github.com/FasterXML/jackson-databind/blob/e59194aaff0a6e520184138924c69045160ee9d9/src/main/java/com/fasterxml/jackson/databind/type/TypeFactory.java), according to [the javadoc](https://fasterxml.github.io/jackson-databind/javadoc/2.2.0/com/fasterxml/jackson/databind/JavaType.html).

[this](https://github.com/FasterXML/jackson-databind/blob/e59194aaff0a6e520184138924c69045160ee9d9/src/main/java/com/fasterxml/jackson/databind/type/TypeFactory.java#L1200) seems relevant.

There are several `JavaType` subclasses, `CollectionLikeType` would be good.

I found [this way](https://github.com/FasterXML/jackson-databind/blob/e59194aaff0a6e520184138924c69045160ee9d9/src/main/java/com/fasterxml/jackson/databind/type/TypeFactory.java#L1322) where you get a collection type built, and sure enough it checks for `Collection.class`. There's also [something for arrays](https://github.com/FasterXML/jackson-databind/blob/e59194aaff0a6e520184138924c69045160ee9d9/src/main/java/com/fasterxml/jackson/databind/type/TypeFactory.java#L1233).

So it seems we may have to submit a patch for jackson-databind... We could suggest that they could also accept as a criteria for a collection implementation of `java.util.Iterable`, but they may be worried about back-compatibility...

What do you think?

**Comment by ruslansennov** [comment]
> So it seems we may have to submit a patch for jackson-databind... We could suggest that they could also accept as a criteria for a collection implementation of java.util.Iterable, but they may be worried about back-compatibility...

I believe this is right way, because it seems we can't do anything here in Javaslang.
We can start with opening issue with description of our problem. Could you create it?

**Comment by emmanueltouzery** [comment]
github did link the issue, but in case you did not get notified, I opened https://github.com/FasterXML/jackson-databind/issues/1430. Let's see what they suggest...

**Comment by ruslansennov** [comment]
Thank you!

**Comment by emmanueltouzery** [comment]
i don't know if you saw, we got a [pretty amazing answer](https://github.com/FasterXML/jackson-databind/issues/1430#issuecomment-255810690) on the upstream bug. 
From what I can see, `CollectionLikeType` does return `true` for `isContainerType()` so it should work I think.

I've tried myself to make javaslang `List` a `CollectionLikeType`, but I broke a huge number of tests with that (3 failures, 21 errors):

    test1(javaslang.jackson.datatype.ScalarTest)  Time elapsed: 0.003 sec  <<< ERROR!
    com.fasterxml.jackson.databind.JsonMappingException: Can not find a Value deserializer for abstract type [collection-like type; class javaslang.collection.List, contains [simple type, class java.lang.Integer]]

If that can help, what I tried [is there](https://github.com/emmanueltouzery/javaslang-jackson/tree/collection_like_broke_it).

If you think I'm not that far from making it, or if you don't have the time, I can try to make this work, but I think I'd need some guidance from you, otherwise it'll take me inordinate amounts of time :-(

**Comment by ruslansennov** [comment]
Hi Emmanuel

First of all, `JavaslangTypeModifier` should be modified on something like this:
```java
final Class<?> raw = type.getRawClass();
if (List.class.isAssignableFrom(raw)) {
   return CollectionLikeType.construct(
         raw, type.containedTypeOrUnknown(0));
}
return type;
```
because in fact `javaslang.collection.List` instance represents by `javaslang.collection.List$Cons` implementation. And here we can observe next problem: Jackson doesn't find custom serializer if serializable type is container type (see [this](https://github.com/FasterXML/jackson-databind/blob/master/src/main/java/com/fasterxml/jackson/databind/ser/BasicSerializerFactory.java#L607) cycle). It seems this can be solved with implementing `findCollectionLikeSerializer()` method in `JavaslangSerializers`

I believe this is right way :)

Last few days I have not enough time for Javaslang projects, but I'll take a look on this issue soon.
