### ISSUE TITLE
Ensure consistency with JacksonScalaModule's Either serialization/deserialization.

### ISSUE THREAD

**Issue by Diagoras** [javaslang/javaslang-jackson#98]
This project looks to represent Either types using "left" and "right" in JSON, where the [JacksonScalaModule](https://github.com/FasterXML/jackson-module-scala) instead uses "l" and "r". Seamless compatibility between these projects would be really nice to have, but would require one of two changes:

1. If you're willing to break backwards compatibility, moving to using "l" and "r" would solve this problem.

2. Otherwise, supporting deserialization of "l" and "r" into an Either would ensure at least programmatic compatibility between the two JSON representations.

[See the related JacksonScala issue here.](https://github.com/FasterXML/jackson-module-scala/issues/303#issuecomment-264993781)

**Comment by ruslansennov** [comment]
Hi @Diagoras 
Like you I prefer `"left"` and `"right"` instead of `"l"` and `"r"`. Also we have to keep backwards compatibility. I believe your second proposal makes sense. Could you make PR?

**Comment by Diagoras** [comment]
Sure, I'll try to get on that the next time I'm free.
